spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 235689
    url: jdbc:mysql://localhost:3306/book?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

  jpa:
    show-sql: true

logging:
  pattern:
    console: "%d - %msg%n"
  path: /var/log/tomcat/

server:
  port: 8080
  servlet:
    context-path: /book